# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crab < Formula
  desc "A versatile tool to crawl dozens of URLs from a given source, like a sitemap or an URL list.
"
  homepage "https://github.com/atomicptr/crab"
  version "1.4.3"

  on_macos do
    url "https://github.com/atomicptr/crab/releases/download/v1.4.3/crab_1.4.3_darwin_amd64.tar.gz"
    sha256 "5dbf4f21f3378c25b259bb0be1382bcddfe353c1094bda666493e54bb05a6e28"

    def install
      bin.install "crab"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Crab
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/atomicptr/crab/releases/download/v1.4.3/crab_1.4.3_linux_amd64.tar.gz"
        sha256 "34ea8fde425b9fe6db62e8280da6b4f149eafe269e74af5aacf4bf5e92659c65"

        def install
          bin.install "crab"
        end
      end
    end
  end
end
