# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crab < Formula
  desc "A versatile tool to crawl dozens of URLs from a given source, like a sitemap or an URL list.
"
  homepage "https://github.com/atomicptr/crab"
  version "1.3.2"

  on_macos do
    url "https://github.com/atomicptr/crab/releases/download/v1.3.2/crab_1.3.2_Darwin_x86_64.tar.gz"
    sha256 "574234279a60497df19d9af2636d4993a81c60c1d07634f1427ee39fe2dc786b"

    def install
      bin.install "crab"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Crab
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/atomicptr/crab/releases/download/v1.3.2/crab_1.3.2_Linux_x86_64.tar.gz"
      sha256 "37d62e92c3bed02674a38a4e3ed9068969caa871818d84406ae73cee51379e4a"

      def install
        bin.install "crab"
      end
    end
  end
end
