# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmplr < Formula
  desc "Quickly create new files from templates
"
  homepage "https://github.com/atomicptr/tmplr"
  version "0.3.1"
  license "GPL-3.0-or-later"

  on_macos do
    url "https://github.com/atomicptr/tmplr/releases/download/v0.3.1/tmplr_0.3.1_darwin_amd64.tar.gz"
    sha256 "be81cad937af33f3a80635d8817ca4a5f3609767f61e0cfabbf143be725a4c11"

    def install
      bin.install "tmplr"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tmplr
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/atomicptr/tmplr/releases/download/v0.3.1/tmplr_0.3.1_linux_amd64.tar.gz"
        sha256 "daa8308d58bf73de6c162999d62cc51957d66532ca915b30c03a4adc4be8fc98"

        def install
          bin.install "tmplr"
        end
      end
    end
  end
end
