# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmplr < Formula
  desc "Quickly create new files from templates
"
  homepage "https://github.com/atomicptr/tmplr"
  version "0.3.2"
  license "GPL-3.0-or-later"

  on_macos do
    url "https://github.com/atomicptr/tmplr/releases/download/v0.3.2/tmplr_0.3.2_darwin_amd64.tar.gz"
    sha256 "c6811be46196b3c45aa0ed9ec06b4e6ead1d07d27291c15422dee82633464fe5"

    def install
      bin.install "tmplr"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tmplr
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/atomicptr/tmplr/releases/download/v0.3.2/tmplr_0.3.2_linux_amd64.tar.gz"
        sha256 "faac031317daab51fc19eae9d7e3670f4affbea095439a6cb4ce3c6757395d6c"

        def install
          bin.install "tmplr"
        end
      end
    end
  end
end
