# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmplr < Formula
  desc "Quickly create new files from templates
"
  homepage "https://github.com/atomicptr/tmplr"
  version "0.2.1"
  license "GPL-3.0-or-later"

  on_macos do
    url "https://github.com/atomicptr/tmplr/releases/download/v0.2.1/tmplr_0.2.1_darwin_amd64.tar.gz"
    sha256 "a9b62b179bef2587fc4309b0a06817c5da917d42a233f3953c8871637fd52ebd"

    def install
      bin.install "tmplr"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tmplr
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/atomicptr/tmplr/releases/download/v0.2.1/tmplr_0.2.1_linux_amd64.tar.gz"
        sha256 "76ce4549296aa72a1db514db591c653eab42a81ebb44ae628738bb6d914e886f"

        def install
          bin.install "tmplr"
        end
      end
    end
  end
end
